### ISSUE TITLE
[feature request] Replotting functionality

### ISSUE THREAD

**Issue by bartaspoz** [ocruzv/chia-plot-manager#1]
It would be great to have the replotting capabilities.
Functionality where you provide dir's with old plots, and plotter wil automatically delete old plots one by one and create new portable plots in the new directory.
I think replotting will be the next big thing, and people will struggle with getting this done correctly.

There is a plotter with such feture implemented already, but it is for Windows, would be great to have it also on this plotter:
https://github.com/MrPig91/PSChiaPlotter

**Comment by ocruzv** [comment]
That makes a lot of sense to me!

I'll work to implement that feature ASAP
