### ISSUE TITLE
Stops generating pooled plots

### ISSUE THREAD

**Issue by Elbers60** [ocruzv/chia-plot-manager#10]
Hello, the plot manager appears to be making the first set of plots with the pool address, but then reverting to the public pool key once those are complete. Please help.

**Comment by ocruzv** [comment]
We have a bug right now where the changes in settings are not reflected immediately to the plotter. To fix it you can restart the app every time you update your settings.

I'll release a new version with that fixed in a couple of days.

**Comment by ocruzv** [comment]
Fixed in the latest release!
