### ISSUE TITLE
[feature request] several final directories

### ISSUE THREAD

**Issue by CityJumperAC** [ocruzv/chia-plot-manager#3]
I Would love to be able to define more than one final directory.
if one is full, coninue with the nexr, or better balance the usage!

greetz
michael

**Comment by ocruzv** [comment]
That makes sense. Right now we can have different final directories creating different workers, but what you're saying makes sense to me too, I'll add that feature to the roadmap

**Comment by sours1000** [comment]
What about this feature?
I recommend you to look into implementation of this feature in this script: https://gist.github.com/Michael-Stoner/9f69e9cd0e1f82dc71aadbc9d5d4ae75

**Comment by bartaspoz** [comment]
Bumping up this issue. If this plotter is inspired by Swar's plot manager then multiple final directories should be its main feature. Right not it is no more than a gui for standard plotter and I see no advantage of using it instaed of standard madmax plotter. 
Swar manager key feature is the ability to define multiple final directories so it can handle them independetly, verify free space and put final plot to a different dir when one is full, and all of this works unattended.

**Comment by ocruzv** [comment]
I've released a new version with this feature in :)
