### ISSUE TITLE
*Feature Request* Total # of Plots to be created per worker (-n option in MadMax)

### ISSUE THREAD

**Issue by roycerezendes** [ocruzv/chia-plot-manager#4]
I would love to have the option to set the total number of plots (-n madmax option) per worker.  For example I know I have a 1 TB drive and can store only 9 plots, so I set the worker to 9 and this way I don't have to monitor it and see when it's about to overflow.  Thank you for your work on this awesome tool!

**Comment by ocruzv** [comment]
As the default behavior, the plotter never stops, I mean, if the worker ended their job, immediately starts a new job.

Also, in the current version the plotter checks if your final destination has enough space (100GiB), if not, it doesn't plot anymore.

Maybe that works for you?

**Comment by roycerezendes** [comment]
Yes ok, I didn't realize it did a space check.  So, I assume I can just set up a Worker for each of the destination drives and let it do it's thing?

**Comment by ocruzv** [comment]
Yes, I think that's a valid strategy!
