### ISSUE TITLE
GUI not appearing, app running in background

### ISSUE THREAD

**Issue by roycerezendes** [ocruzv/chia-plot-manager#5]
I'm sure this is my problem but I can see the app running in the background but the GUI just doesn't show up.  I have 2 Ubuntu Server 20.04 machines and this is only happening to one of them.  Is there some other software I might need to make sure is installed or updated or something that the GUI might depend on?  I installed the .DEB file using Qapt Package Installer.

**Comment by ocruzv** [comment]
Hey @roycerezendes sorry that was completely my mistake. I have released 2 minutes ago a hotfix that should solve your problem. Please download it and try again!

**Comment by roycerezendes** [comment]
Works now, thanks.  However I have an unrelated issue with the Windows EXE.  Windows Defender says it detects a trojan "Trojan:Win32/Sabsik.TE.A!ml" and automatically deletes the file.  I'm not accusing you of anything but do you know why this would show up and if it's safe... 

EDIT:  I updated Windows Defender virus definitions and now it doesn't detect anything, really weird, I don't even know you and I trust your software more than Microsoft Windows Defender...
