### ISSUE TITLE
Windows version Error invoking remote method 'has-enough-space'

### ISSUE THREAD

**Issue by roycerezendes** [ocruzv/chia-plot-manager#6]
Having error with windows version.

Error invoking remote method 'has-enough-space': Error: ENOENT, dist\main\drivespace.exe not found in C:\Program Files\Ocruzv Chia Plot Manager\resources\app.asar

**Comment by ocruzv** [comment]
Hello my friend. I had a problem with the Windows binaries and since I don't use Windows I was not aware of that. 

Please re-download the latest version for windows that is fixed now!!

**Comment by roycerezendes** [comment]
It seems to be working now, thanks.
