### ISSUE TITLE
Plotting 1 at a time, not automatically starting next plot

### ISSUE THREAD

**Issue by roycerezendes** [ocruzv/chia-plot-manager#7]
Using Ubuntu, attempting to replot a full drive.  First plot is created fine and then it just ends and I have to click start plotting again to continue after each plot is made.

**Comment by ocruzv** [comment]
This is still happening to you in the latest version?

Please ensure you don't have enabled the option to stop plotting after the current queue

**Comment by roycerezendes** [comment]
When I put this comment I had the latest version and it still wasn't working, I definitely did not choose that option for it to stop.

**Comment by roycerezendes** [comment]
Restarting the machine fixed the problem somehow.  Plots are being created 1 after the other now.
